# Docs: https://github.com/thedodd/trunk/blob/master/Trunk.toml

# Build tailwind css via hooks
# [[hooks]]
# stage = "pre_build"
# command = "sh"
# command_arguments = ["-c", "npx tailwindcss -i index.css -o style/output.css"]

[serve]
address = "127.0.0.1"
port = 1420
open = false

[build]
filehash = false
release = true
